bestofn_n: 3
bestofn_temperature: 0.6
bestofn_max_tokens: 40960
bestofn_rating_type: "absolute"
planning_n: 2
planning_m: 4
planning_temperature_step1: 1.0
planning_temperature_step2: 1.0
planning_temperature_direct_resp: 0.6
planning_temperature_step3: 1.0
planning_temperature_step4: 0.5
planning_max_tokens_step1: 40960
planning_max_tokens_step2: 40960
planning_max_tokens_direct_resp: 32768
planning_max_tokens_step3: 40960
planning_max_tokens_step4: 40960
use_plan_diversity: False
rating_model: null
use_reasoning_fallback: True
num_of_retries: 2
print_output: true