bestofn_n: 3
bestofn_temperature: 0.6
bestofn_max_tokens: 20480
bestofn_rating_type: "majority"
planning_n: 2
planning_m: 4
planning_temperature_step1: 0.8
planning_temperature_step2: 0.8
planning_temperature_direct_resp: 0.6
planning_temperature_step3: 0.8
planning_temperature_step4: 0.8
planning_max_tokens_step1: 28672
planning_max_tokens_step2: 24576
planning_max_tokens_direct_resp: 32768
planning_max_tokens_step3: 20481
planning_max_tokens_step4: 20482
use_plan_diversity: False
rating_model: null
use_reasoning_fallback: False
num_of_retries: 0
print_output: False