bestofn_n: 3
bestofn_temperature: 0.1
bestofn_max_tokens: 4096
bestofn_rating_type: "absolute"  # or "pairwise", "majority"
planning_n: 3
planning_m: 6
planning_temperature_step1: 0.55
planning_temperature_step2: 0.25
planning_temperature_direct_resp: 0.1
planning_temperature_step3: 0.1
planning_temperature_step4: 0
planning_max_tokens_step1: 4096
planning_max_tokens_step2: 4096
planning_max_tokens_direct_resp: 4096
planning_max_tokens_step3: 4096
planning_max_tokens_step4: 4096
use_plan_diversity: False
rating_model: null
use_reasoning_fallback: False
num_of_retries: 0
print_output: False